USE [master]
GO

CREATE DATABASE [TaxManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaxManagement', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TaxManagement.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TaxManagement_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TaxManagement_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TaxManagement] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaxManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaxManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaxManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaxManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaxManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaxManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaxManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaxManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaxManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaxManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaxManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaxManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaxManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaxManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaxManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaxManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaxManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaxManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaxManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaxManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaxManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaxManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaxManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaxManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [TaxManagement] SET  MULTI_USER 
GO

ALTER DATABASE [TaxManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaxManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaxManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaxManagement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TaxManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TaxManagement] SET  READ_WRITE 
GO

USE [TaxManagement]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Transaction](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Account] [varchar](max) NOT NULL,
	[Description] [varchar](max) NOT NULL,
	[CurrencyCode] [char](3) NOT NULL,
	[Amount] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




